spring:
  application:
    name: pilae-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ec2-54-83-1-101.compute-1.amazonaws.com:5432/d4i46i1a76b73k?user=wjtyvwvaefahuq&password=61a66c4b254ff71ee5258d54378bc5e84ebfd2288960ee906d00af8f0e422c93&sslmode=require}
    driver-class-name: org.postgresql.Driver
    platform: postgres
  flyway:
    baseline-version: 1.0
    baseline-on-migrate: true
    check-location: false
    sqlMigrationSuffixes: .sql
    schemas: public
    locations: classpath:db/migration,classpath:db/update