package main.com.example.multimodule.transversal.mensajes;

public class CodigosMensajes {

	private CodigosMensajes() {

	}

	public static final class CodigosPaisDominioReglaValidacion {

		private CodigosPaisDominioReglaValidacion() {
		}

		public static final String USUARIO_ERROR_CODIGO_PAIS_ES_OBLIGATORIO = "USUARIO_ERROR_CODIGO_PAIS_ES_OBLIGATORIO";
		public static final String TECNICO_ERROR_CODIGO_PAIS_ES_OBLIGATORIO = "TECNICO_ERROR_CODIGO_PAIS_ES_OBLIGATORIO";
		public static final String TECNICO_ERROR_CODIGO_PAIS_NO_CONTIENE_SOLO_DIGITOS = "TECNICO_ERROR_CODIGO_PAIS_NO_CONTIENE_SOLO_DIGITOS";
	}

	public static final class CodigosPaisEnsambladorDTO {
		private CodigosPaisEnsambladorDTO() {
		}

		public static final String USUARIO_DOMINIO_PAIS_ES_OBLIGATORIO = "USUARIO_DOMINIO_PAIS_ES_OBLIGATORIO";
		public static final String TECNICO_DOMINIO_PAIS_ES_OBLIGATORIO = "TECNICO_DOMINIO_PAIS_ES_OBLIGATORIO";
		public static final String USUARIO_DTO_PAIS_ES_OBLIGATORIO = "USUARIO_DTO_PAIS_ES_OBLIGATORIO";
		public static final String TECNICO_DTO_PAIS_ES_OBLIGATORIO = "TECNICO_DTO_PAIS_ES_OBLIGATORIO";
		public static final String USUARIO_REGLA_PAIS_ES_OBLIGATORIO = "USUARIO_REGLA_PAIS_ES_OBLIGATORIO";
		public static final String TECNICO_REGLA_PAIS_ES_OBLIGATORIO = "TECNICO_REGLA_PAIS_ES_OBLIGATORIO";
	}

	public static final class CodigosPaisEnsambladorEntidad {
		private CodigosPaisEnsambladorEntidad() {
		}

		public static final String USUARIO_DOMINIO_PAIS_ES_OBLIGATORIO_ENSA = "USUARIO_DOMINIO_PAIS_ES_OBLIGATORIO_ENSA";
		public static final String TECNICO_DOMINIO_PAIS_ES_OBLIGATORIO_ENSA = "TECNICO_DOMINIO_PAIS_ES_OBLIGATORIO_ENSA";
		public static final String USUARIO_ENTIDAD_PAIS_ES_OBLIGATORIO_ENSA = "USUARIO_ENTIDAD_PAIS_ES_OBLIGATORIO_ENSA";
		public static final String TECNICO_ENTIDAD_PAIS_ES_OBLIGATORIO_ENSA = "TECNICO_ENTIDAD_PAIS_ES_OBLIGATORIO_ENSA";
	}

	public static final class CodigosPaisNegocioImplementacion {
		private CodigosPaisNegocioImplementacion() {
		}

		public static final String USUARIO_PAIS_OBLIGATORIO_CREAR = "USUARIO_PAIS_OBLIGATORIO_CREAR";
		public static final String TECNICO_PAIS_OBLIGATORIO_CREAR = "TECNICO_PAIS_OBLIGATORIO_CREAR";
		public static final String USUARIO_PAIS_CODIGO_EXISTE_CREAR = "USUARIO_PAIS_CODIGO_EXISTE_CREAR";
		public static final String TECNICO_PAIS_CODIGO_EXISTE_CREAR = "TECNICO_PAIS_CODIGO_EXISTE_CREAR";
		public static final String USUARIO_PAIS_NOMBRE_EXISTE_CREAR = "USUARIO_PAIS_NOMBRE_EXISTE_CREAR";
		public static final String TECNICO_PAIS_NOMBRE_EXISTE_CREAR = "TECNICO_PAIS_NOMBRE_EXISTE_CREAR";
		public static final String USUARIO_PAIS_OBLIGATORIO_ACTUALIZAR = "USUARIO_PAIS_OBLIGATORIO_ACTUALIZAR";
		public static final String TECNICO_PAIS_OBLIGATORIO_ACTUALIZAR = "TECNICO_PAIS_OBLIGATORIO_ACTUALIZAR";
		public static final String USUARIO_PAIS_CODIGO_NO_EXISTE_ACTUALIZAR = "USUARIO_PAIS_CODIGO_NO_EXISTE_ACTUALIZAR";
		public static final String TECNICO_PAIS_CODIGO_NO_EXISTE_ACTUALIZAR = "TECNICO_PAIS_CODIGO_NO_EXISTE_ACTUALIZAR";
		public static final String USUARIO_PAIS_NOMBRE_EXISTE_ACTUALIZAR = "USUARIO_PAIS_NOMBRE_EXISTE_ACTUALIZAR";
		public static final String TECNICO_PAIS_NOMBRE_EXISTE_ACTUALIZAR = "TECNICO_PAIS_NOMBRE_EXISTE_ACTUALIZAR";
		public static final String USUARIO_PAIS_OBLIGATORIO_ELIMINAR = "USUARIO_PAIS_OBLIGATORIO_ELIMINAR";
		public static final String TECNICO_PAIS_OBLIGATORIO_ELIMINAR = "TECNICO_PAIS_OBLIGATORIO_ELIMINAR";
		public static final String USUARIO_PAIS_CODIGO_NO_EXISTE_ELIMINAR = "USUARIO_PAIS_CODIGO_NO_EXISTE_ELIMINAR";
		public static final String TECNICO_PAIS_CODIGO_NO_EXISTE_ELIMINAR = "TECNICO_PAIS_CODIGO_NO_EXISTE_ELIMINAR";
	}

	public static final class CodigosPaisFachadaImplementacion {
		private CodigosPaisFachadaImplementacion() {
		}

		public static final String USUARIO_PAIS_DTO_OBLIGATORIO_CREAR = "USUARIO_PAIS_DTO_OBLIGATORIO_CREAR";
		public static final String TECNICO_PAIS_DTO_OBLIGATORIO_CREAR = "TECNICO_PAIS_DTO_OBLIGATORIO_CREAR";
		public static final String USUARIO_PAIS_DTO_OBLIGATORIO_ACTUALIZAR = "USUARIO_PAIS_DTO_OBLIGATORIO_ACTUALIZAR";
		public static final String TECNICO_PAIS_DTO_OBLIGATORIO_ACTUALIZAR = "TECNICO_PAIS_DTO_OBLIGATORIO_ACTUALIZAR";
		public static final String USUARIO_PAIS_DTO_OBLIGATORIO_ELIMINAR = "USUARIO_PAIS_DTO_OBLIGATORIO_ELIMINAR";
		public static final String TECNICO_PAIS_DTO_OBLIGATORIO_ELIMINAR = "TECNICO_PAIS_DTO_OBLIGATORIO_ELIMINAR";

	}
	
	public static final class CodigosPaisControlador {
		private CodigosPaisControlador() {
		}

		public static final String USUARIO_ERROR_INESPERADO_CREAR_EQUIPO = "USUARIO_ERROR_INESPERADO_CREAR_EQUIPO";
		public static final String USUARIO_INFORMACION_CREAR_EQUIPO = "USUARIO_INFORMACION_CREAR_EQUIPO";
		public static final String USUARIO_INFORMACION_OBTENER_EQUIPO = "USUARIO_INFORMACION_OBTENER_EQUIPO";

	}

}
