package main.com.example.multimodule.transversal.mensajes;

public class CodigosMensajes {

	private CodigosMensajes() {

	}

	
	public static final class CodigosEquipoControlador {
		private CodigosEquipoControlador() {
		}

		public static final String USUARIO_ERROR_INESPERADO_CREAR_EQUIPO = "USUARIO_ERROR_INESPERADO_CREAR_EQUIPO";
		public static final String USUARIO_INFORMACION_CREAR_EQUIPO = "USUARIO_INFORMACION_CREAR_EQUIPO";
		public static final String USUARIO_ERROR_DATOS_VACIOS_CREAR_EQUIPO = "USUARIO_ERROR_DATOS_VACIOS_CREAR_EQUIPO";

		public static final String USUARIO_ERROR_INESPERADO_ACTUALIZAR_EQUIPO = "USUARIO_ERROR_INESPERADO_ACTUALIZAR_EQUIPO";
		public static final String USUARIO_INFORMACION_ACTUALIZAR_EQUIPO = "USUARIO_INFORMACION_ACTUALIZAR_EQUIPO";
		public static final String USUARIO_ERROR_DATOS_VACIOS_ACTUALIZAR_EQUIPO = "USUARIO_ERROR_DATOS_VACIOS_ACTUALIZAR_EQUIPO";

		public static final String USUARIO_ERROR_INESPERADO_OBTENER_EQUIPO = "USUARIO_ERROR_INESPERADO_OBTENER_EQUIPO";
		public static final String USUARIO_INFORMACION_OBTENER_EQUIPO = "USUARIO_INFORMACION_OBTENER_EQUIPO";

		public static final String USUARIO_ERROR_INESPERADO_ELIMINAR_EQUIPO = "USUARIO_ERROR_INESPERADO_ELIMINAR_EQUIPO";
		public static final String USUARIO_INFORMACION_ELIMINAR_EQUIPO = "USUARIO_INFORMACION_ELIMINAR_EQUIPO";
	}

	public static final class CodigosDeporteControlador {
		private CodigosDeporteControlador() {
		}

		public static final String USUARIO_ERROR_INESPERADO_CREAR_DEPORTE = "USUARIO_ERROR_INESPERADO_CREAR_DEPORTE";
		public static final String USUARIO_INFORMACION_CREAR_DEPORTE = "USUARIO_INFORMACION_CREAR_DEPORTE";
		public static final String USUARIO_ERROR_DATOS_VACIOS_CREAR_DEPORTE = "USUARIO_ERROR_DATOS_VACIOS_CREAR_DEPORTE";

		public static final String USUARIO_ERROR_INESPERADO_ACTUALIZAR_DEPORTE = "USUARIO_ERROR_INESPERADO_ACTUALIZAR_DEPORTE";
		public static final String USUARIO_INFORMACION_ACTUALIZAR_DEPORTE = "USUARIO_INFORMACION_ACTUALIZAR_DEPORTE";
		public static final String USUARIO_ERROR_DATOS_VACIOS_ACTUALIZAR_DEPORTE = "USUARIO_ERROR_DATOS_VACIOS_ACTUALIZAR_DEPORTE";

		public static final String USUARIO_ERROR_INESPERADO_OBTENER_DEPORTE = "USUARIO_ERROR_INESPERADO_OBTENER_DEPORTE";
		public static final String USUARIO_INFORMACION_OBTENER_DEPORTE = "USUARIO_INFORMACION_OBTENER_DEPORTE";

		public static final String USUARIO_ERROR_INESPERADO_ELIMINAR_DEPORTE = "USUARIO_ERROR_INESPERADO_ELIMINAR_DEPORTE";
		public static final String USUARIO_INFORMACION_ELIMINAR_DEPORTE = "USUARIO_INFORMACION_ELIMINAR_DEPORTE";
	}

	public static final class CodigosJugadorControlador {
		private CodigosJugadorControlador() {
		}
		public static final String USUARIO_ERROR_INESPERADO_CREAR_JUGADOR = "USUARIO_ERROR_INESPERADO_CREAR_JUGADOR";
		public static final String USUARIO_INFORMACION_CREAR_JUGADOR = "USUARIO_INFORMACION_CREAR_JUGADOR";
		public static final String USUARIO_ERROR_DATOS_VACIOS_CREAR_JUGADOR = "USUARIO_ERROR_DATOS_VACIOS_CREAR_JUGADOR";

		public static final String USUARIO_ERROR_INESPERADO_ACTUALIZAR_JUGADOR = "USUARIO_ERROR_INESPERADO_ACTUALIZAR_JUGADOR";
		public static final String USUARIO_INFORMACION_ACTUALIZAR_JUGADOR = "USUARIO_INFORMACION_ACTUALIZAR_JUGADOR";
		public static final String USUARIO_ERROR_DATOS_VACIOS_ACTUALIZAR_JUGADOR = "USUARIO_ERROR_DATOS_VACIOS_ACTUALIZAR_JUGADOR";

		public static final String USUARIO_ERROR_INESPERADO_OBTENER_JUGADOR = "USUARIO_ERROR_INESPERADO_OBTENER_JUGADOR";
		public static final String USUARIO_INFORMACION_OBTENER_JUGADOR = "USUARIO_INFORMACION_OBTENER_JUGADOR";

		public static final String USUARIO_ERROR_INESPERADO_ELIMINAR_JUGADOR = "USUARIO_ERROR_INESPERADO_ELIMINAR_JUGADOR";
		public static final String USUARIO_INFORMACION_ELIMINAR_JUGADOR = "USUARIO_INFORMACION_ELIMINAR_JUGADOR";

	}


	public static final class CodigosMarcadorControlador {
		private CodigosMarcadorControlador() {
		}
		public static final String USUARIO_ERROR_INESPERADO_OBTENER_MARCADOR = "USUARIO_ERROR_INESPERADO_OBTENER_MARCADOR";
		public static final String USUARIO_INFORMACION_OBTENER_MARCADOR = "USUARIO_INFORMACION_OBTENER_MARCADOR";

	}

	public static final class CodigosPartidoControlador {
		private CodigosPartidoControlador() {
		}
		public static final String USUARIO_ERROR_INESPERADO_CREAR_PARTIDO = "USUARIO_ERROR_INESPERADO_CREAR_PARTIDO";
		public static final String USUARIO_INFORMACION_CREAR_PARTIDO = "USUARIO_INFORMACION_CREAR_PARTIDO";
		public static final String USUARIO_ERROR_DATOS_VACIOS_CREAR_PARTIDO = "USUARIO_ERROR_DATOS_VACIOS_CREAR_PARTIDO";

		public static final String USUARIO_ERROR_INESPERADO_ACTUALIZAR_PARTIDO = "USUARIO_ERROR_INESPERADO_ACTUALIZAR_PARTIDO";
		public static final String USUARIO_INFORMACION_ACTUALIZAR_PARTIDO = "USUARIO_INFORMACION_ACTUALIZAR_PARTIDO";
		public static final String USUARIO_ERROR_DATOS_VACIOS_ACTUALIZAR_PARTIDO = "USUARIO_ERROR_DATOS_VACIOS_ACTUALIZAR_PARTIDO";

		public static final String USUARIO_ERROR_INESPERADO_OBTENER_PARTIDO = "USUARIO_ERROR_INESPERADO_OBTENER_PARTIDO";
		public static final String USUARIO_INFORMACION_OBTENER_PARTIDO = "USUARIO_INFORMACION_OBTENER_PARTIDO";

		public static final String USUARIO_ERROR_INESPERADO_CREAR_FIXTURE_PARTIDO = "USUARIO_ERROR_INESPERADO_CREAR_FIXTURE_PARTIDO";
		public static final String USUARIO_INFORMACION_CREAR_FIXTURE_PARTIDO = "USUARIO_INFORMACION_CREAR_FIXTURE_PARTIDO";

		public static final String USUARIO_INFORMACION_JUGAR_PARTIDO = "USUARIO_INFORMACION_JUGAR_PARTIDO";
		public static final String USUARIO_ERROR_DATOS_VACIOS_JUGAR_PARTIDO = "USUARIO_ERROR_DATOS_VACIOS_JUGAR_PARTIDO";

		public static final String USUARIO_ERROR_INESPERADO_ELIMINAR_PARTIDO = "USUARIO_ERROR_INESPERADO_ELIMINAR_PARTIDO";
		public static final String USUARIO_INFORMACION_ELIMINAR_PARTIDO = "USUARIO_INFORMACION_ELIMINAR_PARTIDO";
	}

	public static final class CodigosPosicionControlador {
		private CodigosPosicionControlador() {
		}

		public static final String USUARIO_ERROR_INESPERADO_OBTENER_POSICION = "USUARIO_ERROR_INESPERADO_OBTENER_POSICION";
		public static final String USUARIO_INFORMACION_OBTENER_POSICION = "USUARIO_INFORMACION_OBTENER_POSICION";

	}
	public static final class CodigosTorneoControlador {
		private CodigosTorneoControlador() {
		}
		public static final String USUARIO_ERROR_INESPERADO_CREAR_TORNEO = "USUARIO_ERROR_INESPERADO_CREAR_TORNEO";
		public static final String USUARIO_INFORMACION_CREAR_TORNEO = "USUARIO_INFORMACION_CREAR_TORNEO";
		public static final String USUARIO_ERROR_DATOS_VACIOS_CREAR_TORNEO = "USUARIO_ERROR_DATOS_VACIOS_CREAR_TORNEO";

		public static final String USUARIO_ERROR_INESPERADO_ACTUALIZAR_TORNEO = "USUARIO_ERROR_INESPERADO_ACTUALIZAR_TORNEO";
		public static final String USUARIO_INFORMACION_ACTUALIZAR_TORNEO = "USUARIO_INFORMACION_ACTUALIZAR_TORNEO";
		public static final String USUARIO_ERROR_DATOS_VACIOS_ACTUALIZAR_TORNEO = "USUARIO_ERROR_DATOS_VACIOS_ACTUALIZAR_TORNEO";

		public static final String USUARIO_ERROR_INESPERADO_OBTENER_TORNEO = "USUARIO_ERROR_INESPERADO_OBTENER_TORNEO";
		public static final String USUARIO_INFORMACION_OBTENER_TORNEO = "USUARIO_INFORMACION_OBTENER_TORNEO";

		public static final String USUARIO_ERROR_INESPERADO_ELIMINAR_TORNEO = "USUARIO_ERROR_INESPERADO_ELIMINAR_TORNEO";
		public static final String USUARIO_INFORMACION_ELIMINAR_TORNEO = "USUARIO_INFORMACION_ELIMINAR_TORNEO";
	}

}
